---
title: "Random Numbers"
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    source: embed
    vertical_layout: fill
---

Plot and Data
=======================================================================

Column {.sidebar}
-----------------------------------------------------------------------

### Controls

This is a sidebar on the left.

```{r}
radioButtons("col", h3("Point Color"),
             choices = list("Red" = "red", "Blue" = "blue"),
             selected = "blue")
sliderInput("num", "Number of Values", min = 10, max = 500, value = 200)
numericInput("mean", h3("Mean"), value = 0)
numericInput("sd", h3("Standard Deviation"), value = 1)
```

Column {.tabset}
-----------------------------------------------------------------------

### Plot

This is a tab.

```{r}
dta <- reactive({
  val <- rnorm(input$num, input$mean, input$sd)
  num <- seq(1:input$num)
  dta <- dplyr::bind_cols(num = num, val = val)
})

# Define the output
renderPlot({
  # Create the plot.
  plot(dta(), col = input$col)
})
```

### Table

This is another tab.

```{r}
renderDataTable(
  # Return the table data.
  dta(), 
  options = list(pageLength = 10)
)
```


More Information
=======================================================================

This is a new page. Here, you might want to provide further content.
